CREATE TABLE IF NOT EXISTS chats (
  id INTEGER PRIMARY KEY,
  is_group BOOLEAN NOT NULL DEFAULT 0,
  title TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chats_is_group ON chats(is_group);